title: Semantic Data
description: > # this means to ignore newlines until "baseurl:"
  SematicData.org é o endereço onde a Web 3.0 toma mais sentido. 
  Conteúdos disponibilizados de forma simples e interativa, 
  destinado ao aprendizado referente à Web Semântica e a buscas SPARQL.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://semanticdata.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
